export default {
  SEARCH_ACTION: "SEARCH_ACTION",
  APPLICATION_ERROR: "APPLICATION_ERROR",
  SEARCH_RESULT_RECEIVED: "SEARCH_RESULT_RECEIVED",
  FIND_ALBUM_BY_ARTIST_ACTION: "FIND_ALBUM_BY_ARTIST",
  ALBUM_RESULT_RECEIVED: "ALBUM_RESULT_RECEIVED",
  FIND_ALBUM_DETAILS_BY_ID: "FIND_ALBUM_DETAILS_BY_ID",
  ALBUM_DETAILS_RESULT_RECEIVED: "ALBUM_DETAILS_RESULT_RECEIVED"
};
